In [2]:
import numpy as np

a = [1, 2, 3, 4, 5]
b = np.array(a)

In [3]:
b

array([1, 2, 3, 4, 5])

In [4]:
b**2

array([ 1,  4,  9, 16, 25])

In [5]:
 l = range(1000000)
 len(l)

1000000

In [6]:
%timeit [i**2 for i in l]

266 ms ± 8.36 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
l_np = np.arange(1000000)

In [8]:
len(l_np )

1000000

In [9]:
%timeit l_np ** 2

1.56 ms ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
a = np.array([3, 4, 5, 6])
print(a*2)
print(a.ndim)
print(a.shape)

[ 6  8 10 12]
1
(4,)


In [11]:
c = np.array([1, 2, 3, 4, 5, 6])
b = len(a)
print(b)



4


In [12]:
np.arange(1, 5, 2)

array([1, 3])

In [13]:
print(np.arange(1, 5, 0.5)) # end point is not inclusive
print(np.linspace(0, 100, 12,endpoint = True, retstep = True)) # end point is inclusive

#retstep gives the step between the numbers

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
(array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ]), 9.090909090909092)


In [14]:
type(np.array([1, 2, 3, 4]))

numpy.ndarray

In [15]:
np.array([1, 2, "Aakash"])

array(['1', '2', 'Aakash'], dtype='<U11')

In [16]:
## working with 2D array
m1 = np.array([[1, 2, 3],[4, 5, 6]])
print(m1)
print(m1.ndim)
print(m1.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [17]:
len(np.array([[1,2,3],[4, 5, 6]]))

2

In [18]:
g = np.array([1, 2, 3, 4, 5], ndmin = 2)
print(g)
print(g.ndim)

[[1 2 3 4 5]]
2


In [19]:
m2 = np.arange(1, 13)
print(m2.ndim)


k=m2.reshape(3, 4)
print(k)

1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
c = np.arange(4)
np.resize(c, (2,4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [31]:
a = np.arange(3).reshape(1, 3)
a

array([[0, 1, 2]])

In [22]:
j = np.arange(3)
print(j.T
)

[0 1 2]


In [23]:
#nd array --> flatten
a.flatten()

array([0, 1, 2])

In [24]:
print(np.zeros(3))
print(np.zeros((2,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
print(np.ones((2,3)))
print(np.ones((2,3))*5)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]


In [26]:
#diagonal matrix

a = np.diag([1,2, 3])
b = np.diag(a)
print(a)
print(b)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[1 2 3]


In [27]:
## identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
 m1 = np.array([100, 200, 300, 400, 500, 600])
 m1[[2, 3, 4, 1]]

array([300, 400, 500, 200])

In [29]:
a = np.arange(9).reshape((3, 3))
print(a[[0, 0, 1],[0, 1, 2]])

[0 1 5]


In [30]:
#slicing in numpy
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
a[0,1:3]

array([1, 2])

In [35]:
a = np.arange(6)
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [36]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([8,7,6])
a[2:] = b[::-1]
print(a)

[1 2 6 7 8]


In [53]:
#fancy indexing 
m = np.arange(12).reshape(3,4)
a = m[m < 6]

print(a)

[0 1 2 3 4 5]


TypeError: unsupported operand type(s) for %: 'list' and 'int'