In [ ]:
#splitting, merging, stacking


In [1]:
import numpy as np
x = np.arange(9)

print(x)

[0 1 2 3 4 5 6 7 8]


In [2]:
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [3]:
np.split(x,[3,5,6])

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7, 8])]

In [4]:
x = np.arange(16).reshape(4,4)

In [5]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [7]:
np.hsplit(x,[3,6])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([], shape=(4, 0), dtype=int32)]

In [8]:
np.vsplit(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Stacking

In [12]:
data = np.arange(5)

In [13]:
data

array([0, 1, 2, 3, 4])

In [14]:
np.vstack([data,data,data])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])