In [1]:


import numpy as np


 Broadcating

In [2]:
x = np.array([0, 10, 20, 30])
print(x)
print(x.shape)

[ 0 10 20 30]
(4,)


In [3]:
y = np.array([[1],[2],[3],[4]])
y

array([[1],
       [2],
       [3],
       [4]])

In [4]:
x+y

array([[ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33],
       [ 4, 14, 24, 34]])

In [5]:
x = np.arange(8).reshape(2,4)
y = np.arange(16).reshape(4,4)